### ISSUE TITLE
Error: Address already in use

### ISSUE THREAD

**Issue by arjunmenon** [scottdermott/cordova-plugin-discovery#15]
Hi
If another Upnp app is running, app using this plugin would not work for some reason.

```java
08-27 19:05:51.729 18395 20229 I System.out: Request: M-SEARCH * HTTP/1.1
08-27 19:05:51.729 18395 20229 I System.out: HOST: 239.255.255.250:1900
08-27 19:05:51.730 18395 20229 I System.out: ST:ssdp:all
08-27 19:05:51.730 18395 20229 I System.out: MAN: "ssdp:discover"
08-27 19:05:51.730 18395 20229 I System.out: MX: 2
08-27 19:05:51.730 18395 20229 I System.out: 
08-27 19:05:51.730 18395 20229 I System.out: 
08-27 19:05:51.733 18395 20229 W System.err: java.net.BindException: Address already in use
08-27 19:05:51.733 18395 20229 W System.err: 	at java.net.PlainDatagramSocketImpl.bind0(Native Method)
08-27 19:05:51.733 18395 20229 W System.err: 	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:96)
08-27 19:05:51.733 18395 20229 W System.err: 	at java.net.DatagramSocket.bind(DatagramSocket.java:387)
08-27 19:05:51.733 18395 20229 W System.err: 	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
08-27 19:05:51.734 18395 20229 W System.err: 	at java.net.DatagramSocket.<init>(DatagramSocket.java:295)
08-27 19:05:51.734 18395 20229 W System.err: 	at java.net.DatagramSocket.<init>(DatagramSocket.java:267)
08-27 19:05:51.734 18395 20229 W System.err: 	at com.scott.plugin.cordovaSSDP.search(cordovaSSDP.java:117)
08-27 19:05:51.734 18395 20229 W System.err: 	at com.scott.plugin.serviceDiscovery$1.run(serviceDiscovery.java:23)
08-27 19:05:51.734 18395 20229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-27 19:05:51.734 18395 20229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-27 19:05:51.734 18395 20229 W System.err: 	at java.lang.Thread.run(Thread.java:760)
```

I have Bubble Upnp. If I also open my app with this plugin, it would return this error.
But if Bubble Upnp is closed, it works fine.

**Comment by scottdermott** [comment]
Yeah, you can only create one listener per port (in this case 1900)
Handle gracefully in your app
