### ISSUE TITLE
app has stopped message 

### ISSUE THREAD

**Issue by yuribaril** [scottdermott/cordova-plugin-discovery#8]
My app crashes when I run getNetworkServices, any help?
I see in the log the following error:

FATAL EXCEPTION: pool-1-thread-2
Process: com.ionicframework.beamremote860786, PID: 29910
ava.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
	at com.loopj.android.http.AsyncHttpResponseHandler.sendMessage(AsyncHttpResponseHandler.java:401)
	at com.loopj.android.http.AsyncHttpResponseHandler.sendFailureMessage(AsyncHttpResponseHandler.java:319)
	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
	at com.loopj.android.http.SyncHttpClient.sendRequest(SyncHttpClient.java:95)
	at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:1078)
	at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:1065)
	at com.scott.plugin.cordovaSSDP.createServiceObjWithXMLData(cordovaSSDP.java:56)
	at com.scott.plugin.cordovaSSDP.search(cordovaSSDP.java:131)
	at com.scott.plugin.serviceDiscovery$1.run(serviceDiscovery.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.scott.plugin.cordovaSSDP$1.onFailure(cordovaSSDP.java:70)
	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359)
	... 12 more

**Comment by yuribaril** [comment]
The first post problem I fixed by adding permissions to AndroidManifext.xml:
"uses-permission android:name="android.permission.INTERNET" /"
It failed on MulticastSocket, I found this by adding catch() to the following:
try {
            multicast = new MulticastSocket(null);
            multicast.bind(srcAddress);
            multicast.setTimeToLive(4);
            multicast.send(discoveryPacket);
        } finally {
            multicast.disconnect();
            multicast.close();
        }

**Comment by lucrua** [comment]
Thank you so much for your help. Just to be clear (and for the record), this is what should be done?

In file cordova-plugin-discovery-master\src\android\serviceDiscovery.java, add near to line 27:
``` java
               public void run() {
                  try{
                      mCordovaSSDP.search(service,callbackContext);
                    }catch(IOException e){
                      e.printStackTrace();
                    }
                    catch(Exception e1){ }
               }
``` 
And seems that is necessary to delete and add again the plugin, right?
```
phonegap plugin remove com.scott.serviceDiscovery
phonegap plugin add ../cordova-plugin-discovery-master
```

**Comment by NBroomfield** [comment]
I've got the same issue using the plugin ion Ionic, can anyone recommend a well supported SSDP plugin for Ionic?
